language: python
python:
  - 3.6
install:
  - pip install -r requirements/development.txt
script:
  - make test
after_success:
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa
  - git remote add deploy ssh://$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - git push deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_d62a6a9f7e58_key -iv $encrypted_d62a6a9f7e58_iv
    -in sandbox/certificates/id_rsa_fe_travis.enc -out deploy-key -d
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
